Controllers/CursosController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Cursos.Models.Entidades;
using AutoMapper;
using Cursos.Models.ViewModels;
using WebApplication2.Data;
using WebApplication2.Dominio.Interfaces;
using Microsoft.AspNetCore.Authorization;

namespace Cursos.Controllers
{
    public class CursosController : Controller
    {
        
        private readonly IMapper _mapper;
        private readonly ICursosRepository _cursoRepository;
        private readonly IAulasRepository _aulasRepository;
        public CursosController(ICursosRepository cursosRepository, IAulasRepository aulasRepository, IMapper mapper)
        {
            _cursoRepository = cursosRepository;
            _aulasRepository = aulasRepository;
            _mapper = mapper;
        }

        [Authorize]
        public async Task<IActionResult> Manage()
        {
            return View(_cursoRepository.ObterTodos());
        }

      
        public async Task<IActionResult> Details(int id)
        {
           


            if (id == null)
            {
                return NotFound();
            }

            var curso = _cursoRepository.ObterPorId(id);
            CursoViewModel cursoViewModel = new CursoViewModel();
            List<Aula> aulasCurso = _aulasRepository.ObterPorCurso(id);

            if (curso == null)
            {
                return NotFound();
            }

            cursoViewModel.Id = curso.Id;
            cursoViewModel.thumbnail=curso.thumbnail;
            cursoViewModel.nome = curso.nome;
            cursoViewModel.resumo = curso.resumo;
            cursoViewModel.descricao = curso.descricao;
            cursoViewModel.cargaHoraria = curso.cargaHoraria;
            cursoViewModel.publicoAlvo = curso.publicoAlvo;
            cursoViewModel.aulas = aulasCurso;


            return View(cursoViewModel);
        }

        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,thumbnail,nome,resumo,descricao,publicoAlvo,cargaHoraria")] Curso curso)
        {
            if (ModelState.IsValid)
            {
                _cursoRepository.CriarNovo(curso);
                _cursoRepository.Salvar();
                return RedirectToAction(nameof(Index));
            }
            return View(curso);
        }

        [Authorize]
        public async Task<IActionResult> Edit(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var curso = _cursoRepository.ObterPorId(id);
            if (curso == null)
            {
                return NotFound();
            }
            return View(curso);
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,thumbnail,nome,resumo,descricao,publicoAlvo,cargaHoraria")] Curso curso)
        {
            if (id != curso.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _cursoRepository.Atualiza(curso);
                    _cursoRepository.Salvar();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CursoExists(curso.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(curso);
        }

        [Authorize]
        public async Task<IActionResult> Delete(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var curso = _cursoRepository.ObterPorId(id);
            if (curso == null)
            {
                return NotFound();
            }

            return View(curso);
        }

        
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var curso = _cursoRepository.ObterPorId(id);
            _cursoRepository.Deleta(curso);
            _cursoRepository.Salvar();
            return RedirectToAction(nameof(Index));
        }

        private bool CursoExists(int id)
        {
            return _cursoRepository.Exists(id);
        }


        //controllers de páginas publicas 



        public IActionResult Index()
        {
            List<Curso> cursos = _cursoRepository.ObterTodos().OrderBy(c => c.nome).ToList();


            return View(cursos);
        }

        public async Task<IActionResult> CursosDetalhes(int id)
        {



            if (id == null)
            {
                return NotFound();
            }

            var curso = _cursoRepository.ObterPorId(id);
            CursoViewModel cursoViewModel = new CursoViewModel();
            List<Aula> aulasCurso = _aulasRepository.ObterPorCurso(id);

            if (curso == null)
            {
                return NotFound();
            }

            cursoViewModel.Id = curso.Id;
            cursoViewModel.thumbnail = curso.thumbnail;
            cursoViewModel.nome = curso.nome;
            cursoViewModel.resumo = curso.resumo;
            cursoViewModel.descricao = curso.descricao;
            cursoViewModel.cargaHoraria = curso.cargaHoraria;
            cursoViewModel.publicoAlvo = curso.publicoAlvo;
            cursoViewModel.aulas = aulasCurso;


            return View(cursoViewModel);
        }





    }
}

Controllers/PostagensBlogController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Cursos.Models.Entidades;
using WebApplication2.Data;
using WebApplication2.Dominio.Interfaces;
using Microsoft.AspNetCore.Authorization;

namespace Cursos.Controllers
{
    public class PostagensBlogController : Controller
    {
        private readonly IPostagensBlogRepository _postagemBlogRepository;

        public PostagensBlogController(IPostagensBlogRepository postagemBlogRepository)
        {
            _postagemBlogRepository=postagemBlogRepository;
        }

        [Authorize]
        public async Task<IActionResult> Manage()
        {
            return View(_postagemBlogRepository.ObterTodos());
        }

        [Authorize]
        public async Task<IActionResult> Details(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var postagemBlog = _postagemBlogRepository.ObterPorId(id);
            if (postagemBlog == null)
            {
                return NotFound();
            }

            return View(postagemBlog);
        }

        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,tituloPost,imagemCapa,conteudo,autor")] PostagemBlog postagemBlog)
        {
            if (ModelState.IsValid)
            {
                _postagemBlogRepository.CriarNovo(postagemBlog);
                _postagemBlogRepository.Salvar();
                return RedirectToAction(nameof(Index));
            }
            return View(postagemBlog);
        }

        [Authorize]
        public async Task<IActionResult> Edit(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var postagemBlog = _postagemBlogRepository.ObterPorId(id);
            if (postagemBlog == null)
            {
                return NotFound();
            }
            return View(postagemBlog);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,tituloPost,imagemCapa,conteudo,gostei,naoGostei,dataPublicacao,autor")] PostagemBlog postagemBlog)
        {
            if (id != postagemBlog.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _postagemBlogRepository.Atualiza(postagemBlog);
                    _postagemBlogRepository.Salvar();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PostagemBlogExists(postagemBlog.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(postagemBlog);
        }


        [Authorize]
        public async Task<IActionResult> Delete(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var postagemBlog = _postagemBlogRepository.ObterPorId(id);
            if (postagemBlog == null)
            {
                return NotFound();
            }

            return View(postagemBlog);
        }

       
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var postagemBlog = _postagemBlogRepository.ObterPorId(id);
            _postagemBlogRepository.Deleta(postagemBlog);
            _postagemBlogRepository.Salvar();
            return RedirectToAction(nameof(Index));
        }


        [HttpPost, ActionName("Like")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Like(int id)
        {
            var postagemBlog = _postagemBlogRepository.ObterPorId(id);
            postagemBlog.gostei += 1;

            _postagemBlogRepository.Atualiza(postagemBlog);
            _postagemBlogRepository.Salvar();
            return RedirectToAction(nameof(Post), new {@id = id});
        }


        [HttpPost, ActionName("Dislike")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Dislike(int id)
        {
            var postagemBlog = _postagemBlogRepository.ObterPorId(id);
            postagemBlog.naoGostei += 1;

            _postagemBlogRepository.Atualiza(postagemBlog);
            _postagemBlogRepository.Salvar();
            return RedirectToAction(nameof(Post), new { @id = id });
        }

        private bool PostagemBlogExists(int id)
        {
            return _postagemBlogRepository.Exists(id);
        }

    

        public IActionResult Index()
        {
            List<PostagemBlog> postagens = _postagemBlogRepository.ObterTodos();


            return View(postagens);
        }

        public async Task<IActionResult> Post(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var postagemBlog = _postagemBlogRepository.ObterPorId(id);
            if (postagemBlog == null)
            {
                return NotFound();
            }

            return View(postagemBlog);
        }



    }
}

Controllers/ProfessoresController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Cursos.Models.Entidades;
using WebApplication2.Data;
using WebApplication2.Dominio.Interfaces;
using Microsoft.AspNetCore.Authorization;

namespace Cursos.Controllers
{
    public class ProfessoresController : Controller
    {
        //private readonly ApplicationDbContext _context;
        private readonly IProfessoresRepository _professoresRepository;

        public ProfessoresController(IProfessoresRepository professoresRepository)
        {
            _professoresRepository = professoresRepository;
        }

        [Authorize]
        public async Task<IActionResult> Manage()
        {
            return View(_professoresRepository.ObterTodos());
        }


        [Authorize]
        public async Task<IActionResult> Details(int id)
        {
          
            var professor = _professoresRepository.ObterPorId(id);
            if (professor == null)
            {
                return NotFound();
            }

            return View(professor);
        }

        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Professores/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,nome,titulo,sobre,foto,urlFacebook,urlTwitter,urlInstagram")] Professor professor)
        {
            if (ModelState.IsValid)
            {
                _professoresRepository.CriarNovo(professor);
                _professoresRepository.Salvar();
                return RedirectToAction(nameof(Index));
            }
            return View(professor);
        }

        [Authorize]
        public async Task<IActionResult> Edit(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var professor = _professoresRepository.ObterPorId(id);
            if (professor == null)
            {
                return NotFound();
            }
            return View(professor);
        }

        // POST: Professores/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,nome,titulo,sobre,foto,urlFacebook,urlTwitter,urlInstagram")] Professor professor)
        {
           

            if (ModelState.IsValid)
            {
                try
                {
                    _professoresRepository.Atualiza(professor);
                    _professoresRepository.Salvar();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProfessorExists(professor.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(professor);
        }

        [Authorize]
        public async Task<IActionResult> Delete(int id)
        {
          
            var professor = _professoresRepository.ObterPorId(id);
            if (professor == null)
            {
                return NotFound();
            }

            return View(professor);
        }

       
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var professor = _professoresRepository.ObterPorId(id);
            _professoresRepository.Deleta(professor);
            _professoresRepository.Salvar();
            return RedirectToAction(nameof(Index));
        }

        private bool ProfessorExists(int id)
        {
            return _professoresRepository.Exists(id);
        }


        public IActionResult Index()
        {

            List<Professor> professores = _professoresRepository.ObterTodos() ;


            return View(professores);

        }




    }
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

<!DOCTYPE html>
<html lang="pt=BR">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Cursos</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/style.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img class="logocronos img-logo" src="/img/logocronos.gif" alt="..." /> </a>

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">

                    <ul class="navbar-nav flex-grow-1">
                        @if (SignInManager.IsSignedIn(User))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Administração
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <li><a class="dropdown-item" href="/Cursos/Manage">Gerenciar Cursos</a></li>
                                    <li><a class="dropdown-item" href="/Professores/Manage">Gerenciar Professores</a></li>
                                    <li><a class="dropdown-item" href="/PostagensBlog/Manage">Gerenciar Postagens </a></li>
                                    <li>
                                        <a class="dropdown-item" asp-area="Identity" asp-page="/Account/Register">Criar Novo Usuário </a>
                                    </li>
                                </ul>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Página Inicial</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cursos" asp-action="Index">Cursos</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Professores" asp-action="Index">Professores</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="PostagensBlog" asp-action="Index">Blog</a>
                        </li>

                    </ul>

                    <partial name="_LoginPartial" />

                </div>
            </div>
        </nav>
    </header>


    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Cursos - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://kit.fontawesome.com/ff11ebc0f4.js" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>