Models/Entidades/Curso.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Cursos.Models.Entidades
{
    public class Curso
    {
        public Curso()
        {
            Aulas = new HashSet<Aula>();
        }

        [Key]
        public int Id { get; set; }
        [DisplayName("Imagem")]
        public string thumbnail { get; set; }
        [DisplayName("Nome ")]
        public string nome { get; set; }
        [DisplayName("Resumo")]
        [StringLength(150, ErrorMessage = "Limite de 150 caracteres")]
        public string resumo { get; set; }
        [DisplayName("Descrição")]
        [StringLength(500, ErrorMessage = "Limite de 500 caracteres")]
        public string descricao { get; set; }
        [DisplayName("Público Alvo")]
        public string publicoAlvo { get; set; }
        [DisplayName("Carga Horária")]
        [Range(0, int.MaxValue, ErrorMessage ="Não pode cadastrar curso com carga horária negativa")]
        public int cargaHoraria { get; set; }

        public virtual ICollection<Aula> Aulas { get; set; }





    }
}

Models/ViewModels/CursoViewModel.cs
using Cursos.Models.Entidades;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Cursos.Models.ViewModels
{
    public class CursoViewModel
    {
        public int Id { get; set; }
        [DisplayName("Icone do curso")]
        public string thumbnail { get; set; }
        [DisplayName("Nome do curso")]
        public string nome { get; set; }
        [DisplayName("O que você vai aprender")]
        public string resumo { get; set; }
        [DisplayName("Detalhes do curso")]
        public string descricao { get; set; }
        [DisplayName("Público Alvo")]
        public string publicoAlvo { get; set; }
        [DisplayName("Carga Horária")]
        public int cargaHoraria { get; set; }

        public IEnumerable<Aula> aulas { get; set; }
    }
}

Controllers/AulasController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Cursos.Models.Entidades;
using WebApplication2.Data;
using Cursos.Models.ViewModels;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using WebApplication2.Dominio.Interfaces;

namespace Cursos.Controllers
{   [Authorize]
    public class AulasController : Controller
    {
  
        private readonly IAulasRepository _aulasRepository;

        public AulasController(IAulasRepository aulasRepository)
        {
            _aulasRepository = aulasRepository;
  
   
        }

        [Authorize]
        public async Task<IActionResult> Manage(int id)
        {
            if (id != null)
            {
                var aulasPorCurso = new AulaViewModel();

                 
                aulasPorCurso.Aulas = _aulasRepository.ObterPorCurso(id);
                aulasPorCurso.idCurso = id;
                return View(aulasPorCurso);
            }
            else {

                var context = _aulasRepository.ObterTodos();

                return View(context);
            }

          
        }

        [Authorize]
        public async Task<IActionResult> Details(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var aula = _aulasRepository.ObterPorId(id);
            if (aula == null)
            {
                return NotFound();
            }

            return View(aula);
        }

        [Authorize]
        public IActionResult Create(int id)
        {
            
        
            var aula = new Aula();
            aula.cursoId = id;
        
            return View(aula);
        }

       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("numeroOrdem,titulo,descricao, cursoId")] Aula aula)
        {
          
            if (ModelState.IsValid)
            {
                _aulasRepository.CriarNovo(aula);
                _aulasRepository.Salvar();
                return RedirectToAction(nameof(Manage), new {id=aula.cursoId});
            }
         
            return View(aula);
        }

        [Authorize]
        public async Task<IActionResult> Edit(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var aula = _aulasRepository.ObterPorId(id);
            if (aula == null)
            {
                return NotFound();
            }
            return View(aula);
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,numeroOrdem,titulo,descricao,cursoId")] Aula aula)
        {
            if (id != aula.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _aulasRepository.Atualiza(aula);
                    _aulasRepository.Salvar();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AulaExists(aula.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Manage), new { id = aula.cursoId });
            }
    
            return View(aula);
        }

        [Authorize]
        public async Task<IActionResult> Delete(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var aula = _aulasRepository.ObterPorId(id);
            if (aula == null)
            {
                return NotFound();
            }

            return View(aula);
        }

        
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var aula = _aulasRepository.ObterPorId(id);
            _aulasRepository.Deleta(aula);
            _aulasRepository.Salvar();
            return RedirectToAction(nameof(Manage), new { id = aula.cursoId });
        }

        private bool AulaExists(int id)
        {
            return _aulasRepository.Exists(id);
        }
    }
}

Controllers/CursosController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Cursos.Models.Entidades;
using AutoMapper;
using Cursos.Models.ViewModels;
using WebApplication2.Data;
using WebApplication2.Dominio.Interfaces;
using Microsoft.AspNetCore.Authorization;

namespace Cursos.Controllers
{
    public class CursosController : Controller
    {
        
        private readonly IMapper _mapper;
        private readonly ICursosRepository _cursoRepository;
        private readonly IAulasRepository _aulasRepository;
        public CursosController(ICursosRepository cursosRepository, IAulasRepository aulasRepository, IMapper mapper)
        {
            _cursoRepository = cursosRepository;
            _aulasRepository = aulasRepository;
            _mapper = mapper;
        }

        [Authorize]
        public async Task<IActionResult> Manage()
        {
            return View(_cursoRepository.ObterTodos());
        }

      
        public async Task<IActionResult> Details(int id)
        {
           


            if (id == null)
            {
                return NotFound();
            }

            var curso = _cursoRepository.ObterPorId(id);
            CursoViewModel cursoViewModel = new CursoViewModel();
            List<Aula> aulasCurso = _aulasRepository.ObterPorCurso(id);

            if (curso == null)
            {
                return NotFound();
            }

            cursoViewModel.Id = curso.Id;
            cursoViewModel.thumbnail=curso.thumbnail;
            cursoViewModel.nome = curso.nome;
            cursoViewModel.resumo = curso.resumo;
            cursoViewModel.descricao = curso.descricao;
            cursoViewModel.cargaHoraria = curso.cargaHoraria;
            cursoViewModel.publicoAlvo = curso.publicoAlvo;
            cursoViewModel.aulas = aulasCurso;


            return View(cursoViewModel);
        }

        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,thumbnail,nome,resumo,descricao,publicoAlvo,cargaHoraria")] Curso curso)
        {
            if (ModelState.IsValid)
            {
                _cursoRepository.CriarNovo(curso);
                _cursoRepository.Salvar();
                return RedirectToAction(nameof(Index));
            }
            return View(curso);
        }

        [Authorize]
        public async Task<IActionResult> Edit(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var curso = _cursoRepository.ObterPorId(id);
            if (curso == null)
            {
                return NotFound();
            }
            return View(curso);
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,thumbnail,nome,resumo,descricao,publicoAlvo,cargaHoraria")] Curso curso)
        {
            if (id != curso.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _cursoRepository.Atualiza(curso);
                    _cursoRepository.Salvar();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CursoExists(curso.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(curso);
        }

        [Authorize]
        public async Task<IActionResult> Delete(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var curso = _cursoRepository.ObterPorId(id);
            if (curso == null)
            {
                return NotFound();
            }

            return View(curso);
        }

        
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var curso = _cursoRepository.ObterPorId(id);
            _cursoRepository.Deleta(curso);
            _cursoRepository.Salvar();
            return RedirectToAction(nameof(Index));
        }

        private bool CursoExists(int id)
        {
            return _cursoRepository.Exists(id);
        }


        //controllers de páginas publicas 



        public IActionResult Index()
        {
            List<Curso> cursos = _cursoRepository.ObterTodos().OrderBy(c => c.nome).ToList();


            return View(cursos);
        }

        public async Task<IActionResult> CursosDetalhes(int id)
        {



            if (id == null)
            {
                return NotFound();
            }

            var curso = _cursoRepository.ObterPorId(id);
            CursoViewModel cursoViewModel = new CursoViewModel();
            List<Aula> aulasCurso = _aulasRepository.ObterPorCurso(id);

            if (curso == null)
            {
                return NotFound();
            }

            cursoViewModel.Id = curso.Id;
            cursoViewModel.thumbnail = curso.thumbnail;
            cursoViewModel.nome = curso.nome;
            cursoViewModel.resumo = curso.resumo;
            cursoViewModel.descricao = curso.descricao;
            cursoViewModel.cargaHoraria = curso.cargaHoraria;
            cursoViewModel.publicoAlvo = curso.publicoAlvo;
            cursoViewModel.aulas = aulasCurso;


            return View(cursoViewModel);
        }





    }
}

Views/Cursos/Create.cshtml
@model Cursos.Models.Entidades.Curso


@{
    ViewData["Title"] = "Cadastrar Curso";
}

<section>
    <div>
        <h1 class="text-center">Cadastrar Curso</h1>
        <hr />
    </div>
    <div class="container">
        <div class="card row">
            <div class="card-body col-10 mx-auto">
                <form asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group mb-2">
                        <label asp-for="thumbnail" class="col-sm-2 col-form-label"></label>
                        <input asp-for="thumbnail" class="form-control"/>
                        <span asp-validation-for="thumbnail" class="text-danger"></span>
                    </div>
                    <div class="form-group mb-2">
                        <label asp-for="nome" class="col-sm-2 col-form-label"></label>
                        <input asp-for="nome" class="form-control"/>
                        <span asp-validation-for="nome" class="text-danger"></span>
                    </div>
                    <div class="form-group mb-2">
                        <label asp-for="resumo" class="col-sm-2 col-form-label"></label>
                        <input asp-for="resumo" class="form-control"/>
                        <span asp-validation-for="resumo" class="text-danger"></span>
                    </div>
                    <div class="form-group mb-2">
                        <label asp-for="descricao" class="col-sm-2 col-form-label"></label>
                        <textarea asp-for="descricao" class="form-control"></textarea>
                        <span asp-validation-for="descricao" class="text-danger"></span>
                    </div>
                    <div class="form-group mb-2">
                        <label asp-for="publicoAlvo" class="col-sm-2 col-form-label"></label>
                        <input asp-for="publicoAlvo" class="form-control"/>
                        <span asp-validation-for="publicoAlvo" class="text-danger"></span>
                    </div>
                    <div class="form-group mb-4">
                        <label asp-for="cargaHoraria" class="col-sm-2 col-form-label"></label>
                        <input asp-for="cargaHoraria" class="form-control" />
                        <span asp-validation-for="cargaHoraria" class="text-danger"></span>
                    </div>
                    <div class="form-group row mb-3">
                        <div class="d-grid col-2 ms-auto">
                            <input type="submit" value="cadastrar" class="btn btn-success" />
                        </div>
                        <div class="d-grid col-2 me-auto">
                            <a asp-action="Index" class="btn btn-danger">Cancelar</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/Cursos/CursosDetalhes.cshtml
@model Cursos.Models.ViewModels.CursoViewModel

@{
    ViewData["Title"] = "Detalhes do curso";
}




<div class="p-5 mb-4 bg-light round-3" style="background: url(@Model.thumbnail);">
    <div class="container-fluid py-5" >
        <h1 class="display-5 fw-bold">@Model.nome</h1>
        <p class="col-md-8 fs-4">@Model.resumo</p><a class="btn btn-primary btn-lg" role="button" href="#">Inscreva-se</a>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-6 col-lg-7">
            <p class="lead"><br>@Model.descricao.<br><br></p>
        </div>
        <div class="col-md-6 col-lg-5 col-xl-4 d-lg-flex align-items-lg-center">
            <ul class="list-group">
                <li class="list-group-item"><i class="fas fa-users mr-3"></i><span></span><span> @Model.publicoAlvo</span></li>
                <li class="list-group-item"><i class="fas fa-stopwatch mr-3"></i><span>@Model.cargaHoraria</span></li>
            </ul>
        </div>
    </div>
</div>
<div class="container">
    <h1 class="mb-4 mt-4">Programação</h1>
    <ul class="list-group" >
        @foreach(var item in Model.aulas)
        {
            <li class="list-group-item"><span>@item.titulo</span></li>
        }
        
        
    </ul>
</div>

Views/Cursos/Delete.cshtml
@model Cursos.Models.Entidades.Curso

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Curso</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.thumbnail)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.thumbnail)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.resumo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.resumo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.descricao)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.descricao)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.publicoAlvo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.publicoAlvo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.cargaHoraria)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.cargaHoraria)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Cursos/Details.cshtml
@model Cursos.Models.ViewModels.CursoViewModel

@{
    ViewData["Title"] = "Detalhes do curso";
}




<div class="p-5 mb-4 bg-light round-3" style="background: url(@Model.thumbnail);">
    <div class="container-fluid py-5" >
        <h1 class="display-5 fw-bold text-over-img">@Model.nome</h1>
        <p class="col-md-8 fs-4 text-over-img ">@Model.resumo</p><a class="btn btn-primary btn-lg" role="button" href="#">Inscreva-se</a>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-6 col-lg-7">
            <p class="lead"><br>@Model.descricao.<br><br></p>
        </div>
        <div class="col-md-6 col-lg-5 col-xl-4 d-lg-flex align-items-lg-center">
            <ul class="list-group">
                <li class="list-group-item"><i class="fas fa-users mr-3"></i><strong> Público Alvo: </strong><span> @Model.publicoAlvo</span></li>
                <li class="list-group-item"><i class="fas fa-stopwatch mr-3"></i><strong> Carga Horária: </strong><span>@Model.cargaHoraria</span></li>
            </ul>
        </div>
    </div>
</div>
<div class="container">
    <h1 class="mb-4 mt-4">Programação</h1>
    <ul class="list-group" >
        @foreach(var item in Model.aulas)
        {
            <li class="list-group-item">
                <span class="badge bg-secondary">@item.numeroOrdem</span>
                <span class="fw-bold"> @item.titulo</span>
                <p>@item.descricao</p>
                
            
            </li>
        }
        
        
    </ul>
</div>

Views/Cursos/Edit.cshtml
@model Cursos.Models.Entidades.Curso

@{
    ViewData["Title"] = "Editar Curso";
}

<section>
    <div>
        <h1 class="text-center">Editar Curso</h1>
        <hr />
    </div>
    <div class="container">
        <div class="card row">
            <div class="card-body col-10 mx-auto">
                <form asp-action="Edit">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group mb-2">
                        <label asp-for="thumbnail" class="col-sm-2 col-form-label"></label>
                        <input asp-for="thumbnail" class="form-control"/>
                        <span asp-validation-for="thumbnail" class="text-danger"></span>
                    </div>
                    <div class="form-group mb-2">
                        <label asp-for="nome" class="col-sm-2 col-form-label"></label>
                        <input asp-for="nome" class="form-control"/>
                        <span asp-validation-for="nome" class="text-danger"></span>
                    </div>
                    <div class="form-group mb-2">
                        <label asp-for="resumo" class="col-sm-2 col-form-label"></label>
                        <input asp-for="resumo" class="form-control"/>
                        <span asp-validation-for="resumo" class="text-danger"></span>
                    </div>
                    <div class="form-group mb-2">
                        <label asp-for="descricao" class="col-sm-2 col-form-label"></label>
                        <textarea asp-for="descricao" class="form-control"></textarea>
                        <span asp-validation-for="descricao" class="text-danger"></span>
                    </div>
                    <div class="form-group mb-2">
                        <label asp-for="publicoAlvo" class="col-sm-2 col-form-label"></label>
                        <input asp-for="publicoAlvo" class="form-control"/>
                        <span asp-validation-for="publicoAlvo" class="text-danger"></span>
                    </div>
                    <div class="form-group mb-4">
                        <label asp-for="cargaHoraria" class="col-sm-2 col-form-label"></label>
                        <input asp-for="cargaHoraria" class="form-control"/>
                        <span asp-validation-for="cargaHoraria" class="text-danger"></span>
                    </div>
                    <div class="form-group row mb-3">
                        <div class="d-grid col-2 ms-auto">
                            <input type="submit" value="Salvar" class="btn btn-success" />
                        </div>
                        <div class="d-grid col-2 me-auto">
                            <a asp-action="Index" class="btn btn-danger">Cancelar</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/Cursos/Index.cshtml
@model IEnumerable<Cursos.Models.Entidades.Curso>

@{
    ViewData["Title"] = "Cursos";
}
<div>
    <h1 class="text-center">CURSOS</h1>
</div>


<section>
    <div class="row row-cols-1 row-cols-md-3 row-cols-sm-1 g-4">
        @foreach (var item in Model)
        {
        <div class="col">
            <div class="card h-100 shadow p-3 mb-5 bg-white rounded">
                <img src="@Html.DisplayFor(modelItem => item.thumbnail)" class="img-fluid rounded-start" alt="...">
                <div class="card-body">
                    <h5 class="card-title text-center">@Html.DisplayFor(modelItem => item.nome)</h5>
                    <p class="card-text text-center">@Html.DisplayFor(modelItem => item.resumo)</p>
                    <div class="card-body text-center">
                     <a asp-controller="Cursos" asp-action="Details" asp-route-id="@item.Id" class="btn btn-warning">Veja mais</a>
                    </div>

                </div>
            </div>
        </div>
        }
    </div>
</section>

Views/Cursos/Manage.cshtml
@model IEnumerable<Cursos.Models.Entidades.Curso>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a class="btn btnbtn-outline-primary" asp-action="Create">Criar Curso</a>
</p>



<table class="table table-striped">
    <thead class="thead-Plum">
        <tr>

            <th scope="col">Nome</th>
            <th scope="col">Ações</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {

            <tr>
                <td>@item.nome</td>
                    <td>
                <a class="badge bg-primary" asp-action="Edit" asp-route-id="@item.Id"><i class="fa-solid fa-pen-to-square"></i> Editar</a> |
                <a class="badge bg-warning text-dark" asp-action="Details" asp-route-id="@item.Id"><i class="fa-solid fa-circle-info"></i> Detalhes</a> |
                <a class="badge bg-danger"asp-action="Delete" asp-route-id="@item.Id"><i class="fa-solid fa-trash-can"></i> Deletar</a>
       |
                <a asp-controller="Aulas" asp-action="Manage" asp-route-id="@item.Id">Ver aulas de @item.Id</a>
                </td>
            </tr>

        }

    </tbody>
</table>